name: "Build & Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, linux], [macos-latest], [self-hosted, macOS]]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
    - uses: cachix/cachix-action@v12
      with:
        name: nixpkgs-python
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --keep-going --accept-flake-config --show-trace
