name: "Build & Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, linux, X64], [macos-latest], [self-hosted, macOS, ARM64], [self-hosted, linux, ARM64]]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
      with: 
        install_url: https://nixos-nix-install-tests.cachix.org/serve/r1x1gcvnw0hc9cv531z86pa5lfn8s9jn/install 
        install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
    - uses: cachix/cachix-action@v14
      with:
        name: nixpkgs-python
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --keep-going --accept-flake-config --show-trace
